### ISSUE TITLE
Should this repository be used instead of zenazn/goji?

### ISSUE THREAD

**Issue by davidbarsky** [goji/goji#1]
as the title says.

(love the project, by the way. thanks for working on it!)

**Comment by zenazn** [comment]
Interesting question.

This package is The Future™. It uses `context.Context` and has a couple other interesting changes, and at some point will be the recommended package to use. I also wrote it very recently, make no guarantees for API stability (yet, at least), and while its test coverage is very good it may still have bugs. I also e.g., haven't set up the vanity import it expects (`goji.io`), nor have I set up Travis.

zenazn/goji is time- and battle-tested. I think its interface is lacking in many ways (hence this package), but it works very reliably.

If you're just playing around, I'd recommend having a look at this package, but for code you expect to run in production I'd recommend sticking with zenazn/goji for now. This advice might change in a week or two, but switching shouldn't be too hard.

**Comment by davidbarsky** [comment]
thanks for your response! i'll probably stick with zenazn/goji for now, and migrate over to this new one soon enough.

**Comment by grounded042** [comment]
Just a suggestion - it might be nice to put a blurb with this info in both repo READMEs. While this issue is helpful in clearing up the existence of two repos, it can be confusing having two repos.

**Comment by shardnit** [comment]
Is it still recommended to use zenazn/goji or goji/goji is a "go"?

**Comment by zenazn** [comment]
After many months of baking, I just cut a stable 1.0 release :tada: 

That means I'm now recommending this project over `zenazn/goji`. There's of course no pressing reason for existing projects to switch, and both projects will be maintained indefinitely.
