### ISSUE TITLE
Upgrading from web.C

### ISSUE THREAD

**Issue by scisci** [goji/goji#10]
Hi, I haven't updated in a while and notice that now you use google's context object instead of web.C, is there documentation on how to upgrade?

**Comment by elithrar** [comment]
Keep in mind that Goji v1 (which uses `web.C`) still exists over at https://github.com/zenazn/goji — so there's no need to worry about breaking existing applications if you're still using `go get`. Also have a quick read of Carl's comment here: https://github.com/goji/goji/issues/1#issuecomment-157179877 (in short: Goji v2 is the future, although Goji v1 is primarily feature complete anyway and was unlikely to see any major changes)

If you do want to upgrade from Goji v1 to Goji v2 (this repo) then:

* You'll need to move from `func(web.C, http.ResponseWriter, *http.Request)` signatures to `func(context.Context, http.ResponseWriter, *http.Request)`
* Any custom `web.Match` stuff will need to be changed to use the new `pat` package
* Other pertinent API changes:

```diff
// Getting objects from the request context
- c.Env["key"]
+ ctx.Value("key")

// Setting objects
- c.Env["key"] = someVal
+ ctx = context.WithValue(ctx, "key", someVal)

// Route parameters
- c.URLParams["name"]
+ pat.Param(ctx, "name")

// Creating multiplexers (muxes/routers)
- web.New()
+ goji.NewMux()

// Routes and handlers
- mux.Get("/route", YourHandler)
+ mux.HandleC(pat.Get("/route"), YourHandler) // Use mux.Handle for vanilla http.Handler
```

* `graceful.ListenAndServe` still works out of the box

Hope that helps. You may be able to automate this via some `gofmt` [rewriting](https://golang.org/cmd/gofmt/) or regex find-and-replace in your editor of choice.

If you run into any roadblocks, post some code & your process to date over on the mailing list—https://groups.google.com/forum/#!forum/gojiberries—and I'll be glad to help.

**Comment by scisci** [comment]
Thanks for the info. I didn't realize it was two projects, but am definitely interested in switching to the new one since it adheres to googles context advice.

Any advice on how to handle migrating if I was using some of the basic middleware in the previous version? For instance, I had a few middlewares of the form:

`func(c *web.C, h http.Handler) http.Handler`

would I just switch web.C to context?

**Comment by patbaker82** [comment]
I've just been playing around, but I think this is the basic idea.

```go
	mux.UseC(func(h goji.Handler) goji.Handler {
		fn := func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
			fmt.Println("Start")
			newCtx := context.WithValue(ctx, "foo", "bar")
			h.ServeHTTPC(newCtx, w, r)
			fmt.Println("End")
		}
		return goji.HandlerFunc(fn)
	})
```

**Comment by elithrar** [comment]
That's right - effectively you just replace `func(*web.C, http.Handler)` with `func(goji.Handler) goji.Handler` and call the next handler as needed (or respond with an error, etc). 

Alternatively you can return a type that implements 'goji.Handler` (has a `ServeHTTPC` method) like so: 
https://github.com/goji/csrf/blob/csrf-v2-net-context/csrf.go#L120-L170

**Comment by zenazn** [comment]
This issue hasn't had any traffic in a month or so, so I'm going to close it out. Please feel free to open a new issue (or re-open this one) if you have any difficulty making the transition from Goji 1 to Goji 2!
