### ISSUE TITLE
Alternative middleware signature ?

### ISSUE THREAD

**Issue by vanackere** [goji/goji#12]
Hi,

 Glad to see a new version of goji using context.Context (i'll drop my goji fork once this new version has gotten enough testing) !
In [slim](https://github.com/vanackere/slim) I found very convenient to be able to define middlewares using the following signature:
```go
func(ctx context.Context, w http.ResponseWriter, r *http.Request, next goji.Handler)
```

While is is quite easy to write a wrapper for this, it would be nice to have this signature allowed by default since in my experience if allows to more easily write middlewares. Would you consider either adding a new method .UseM(...) or adding a conversion function ? Trivial adapter below:

```go
type handlerNext struct {
	f    func(_ context.Context, _ http.ResponseWriter, _ *http.Request, next goji.Handler)
	next goji.Handler
}

func (h handlerNext) ServeHTTPC(c context.Context, w http.ResponseWriter, r *http.Request) {
	h.f(c, w, r, h.next)
}

// Middleware converts a func(_ context.Context, _ http.ResponseWriter, _ *http.Request, _ goji.Handler) into a goji middleware
func Middleware(f func(_ context.Context, _ http.ResponseWriter, _ *http.Request, _ goji.Handler)) func(goji.Handler) goji.Handler {
	return func(h goji.Handler) goji.Handler {
		return handlerNext{f, h}
	}
}
```

Thanks for reading this !

**Comment by elithrar** [comment]
Although I don't like this approach, shouldn't next call a handler of the
same type?

**Comment by vanackere** [comment]
I just realized that this issue would probably be much better explained using an exemple:
here follows a simplified panic recovery middleware using the proposed signature, parametrized by a boolean (in debug mode we also want to render the panic stack as html):

```go
func RecoveryMiddleware(debug bool) func(context.Context, http.ResponseWriter, *http.Request, goji.Handler) {
	return func(ctx context.Context, w http.ResponseWriter, r *http.Request, next goji.Handler) {
		defer func() {
			if err := recover(); err != nil {
				fmt.Printf("PANIC: %s\n", err)
				for i := 1; ; i++ { // Skip the expected number of frames
					pc, file, line, ok := runtime.Caller(i + 2)
					if !ok {
						break
					}
					fmt.Printf(" callstack %d: file=%s, line=%d, pc=%x", i, file, line, pc)
				}
				// respond with panic message while in development mode
				var body []byte
				if debug {
					stack := string(fmtStack(3))
					w.Header().Set("Content-Type", "text/html")
					body = []byte(fmt.Sprintf(panicHTML, err, err, stack))
				}

				w.WriteHeader(http.StatusInternalServerError)
				if body != nil {
					w.Write(body)
				}
			}
		}()
		next.ServeHTTPC(ctx, w, r)
	}
}
```

Please don't hesitate to compare this to the same middleware written using the current middleware signature, I'm genuinely interested in which version you find easier to understand !

**Comment by elithrar** [comment]
You can definitely do the above with the current approach—I also think it's
more concise:

func RecoveryMiddleware(debug bool) func(context.Context,
http.ResponseWriter, *http.Request, goji.Handler) {
    return func(ctx context.Context, w http.ResponseWriter, r
*http.Request, next goji.Handler) {
        defer func() {


... becomes:


func RecoveryMiddleware(debug bool) func(next goji.Handler) goji.Handler {
    return func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
        defer func() {


This approach doesn't need an additional "UseM" signature, but the
biggest benefit is that you can accept any goji.Handler "as is".

**Comment by zenazn** [comment]
@vanackere—thanks for the kind words! You'll be happy to know you played a big part in the development of this version of Goji, even if you didn't realize it :)

I considered the alternate middleware signature you suggested, but ultimately decided against it. I liked the simplicity and obvious composability of `func(Handler) Handler`, and it's a teensy bit more efficient to implement (although certainly not enough to matter had that signature been obviously better). The signature you suggest does tend to reduce the number of levels of indentation in many common middleware, but it does so by making the type signature much wider (and different than ~any other type signature in the package).

Ultimately I think Goji could have shipped with either signature and things would have been Just Fine™, but it seems gratuitous to have both, especially given how easy the converter in either direction is to write. In that spirit I'm not interested in adding `UseM` or `UseMC`, although I'd encourage you to document the conversion helper somewhere on the internet in case someone finds it helpful in understanding middleware.
