### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by bfitzsimmons** [goji/goji#13]
I'm getting an error when trying to `go get` this repo.

```bash
$ go get -u github.com/goji/goji
package github.com/goji/goji
	imports goji.io/internal: use of internal package not allowed
```

Any thoughts on how to deal with this? Am I getting the wrong path or package? Is the repo. `go get`-able at this point?

**Comment by elithrar** [comment]
go get goji.io

**Comment by bfitzsimmons** [comment]
That works. Thanks!
