### ISSUE TITLE
Pattern regular expressions. 

### ISSUE THREAD

**Issue by bfitzsimmons** [goji/goji#15]
Is this incarnation of Goji going to grow the ability to match URLs using regular expressions?

**Comment by zenazn** [comment]
Maybe! I haven't gotten around to porting the `regexp`-based `Pattern` implementation over, but it should be straightforward enough, and I hope to get to it eventually. To be honest, I found that I don't really miss it, but perhaps you feel the urgency more than I do.

One really nice thing about the new Goji design, however, is that you can write and use your own `Pattern` implementation—you only need to implement a single method! Let me know if you end up going this route—I'm not sure there are any other `Pattern` implementations out there, and I'd love to know how it goes.

**Comment by bfitzsimmons** [comment]
I'll see how I get along without it. I'll revisit this if I find that I can't.

Thanks for the response.
