### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by elithrar** [goji/goji#16]
Consider this a tracking issue for adding an `examples` directory or (better) some examples on the website.
- [ ] Add a simple example with 2-3 routes and some template rendering. There should be some middleware involved to show how to pass values using `context.Context` between handlers. 
- [ ] A more complex example where Goji is an API server serializing objects to JSON. Possibly show some CORS middleware here, as this is a common use-case in a world of React, Vue, Ember, etc. BoltDB could help in making it a little more "real world" without relying on external dependencies.

I'd be happy to contribute here, but wanted to open this up for discussion first, and for others who might have more time to chip in.

**Comment by ego008** [comment]
@zenazn

**Comment by ess** [comment]
I wouldn't know where to start, but Gritter2 (with promoted and >140-character posts, of course) would be pretty great to see.

:+1:

**Comment by elithrar** [comment]
Great idea @ess. I'll see if I can port that over this weekend and PR it.

**Comment by ottob** [comment]
This would be super helpful! I've found https://github.com/andrew-d/go-webapp-skeleton but more examples would be very welcome.

**Comment by matrixik** [comment]
Also linking to outside examples also would be great (like the one posted by @ottob or https://github.com/metcalf/saypi )

**Comment by ego008** [comment]
Full example https://github.com/ego008/goyoubbs
