### ISSUE TITLE
New Org Repo Request: goji/logger

### ISSUE THREAD

**Issue by elithrar** [goji/goji#17]
I'd like to push https://github.com/elithrar/goji-logger to `goji/logger`.
- Ports the Goji v1 middleware Logger and RequestID to Goji v2
- Makes it available (discoverable) under the organization
- Provides a friendly screenshot of the output

@zenazn

**Comment by elithrar** [comment]
Hey @zenazn - just wanted to follow up on this and see if we can make push this to the goji GitHub org?

**Comment by moorereason** [comment]
@elithrar, can you and @jdoklovic join forces to work on this and #18?  You guys posted these hours apart back in March.

My preference would be to have the logger and the RequestID in separate packages.

**Comment by elithrar** [comment]
Sure. If we are breaking the API for Go 1.7 then we'll need to update the
middleware to suit.

**Comment by zenazn** [comment]
This issue has been idle for quite a few months now, so I'm closing it to keep everything tidy. Since Goji has standardized on `net/http` interfaces, I'm delighted to say that this problem can be solved Mux-agnostically, and no longer needs to be done under the "Goji" umbrella.
