### ISSUE TITLE
New repo request: gojiid

### ISSUE THREAD

**Issue by jdoklovic** [goji/goji#18]
I'd like to have a new repo created under goji called "goji/gojiid"
This repo will contain what's currently in: https://github.com/atlassian/gojiid

The project is "Goji Id", which provides a flexible middleware that puts a requestId in the http Context by either pulling it out of the http request header using custom provided keys, or generating it.

There is a default generator, or a custom generator may be provided.
Finally, it provides a function to pull the id out of the context. This function can be passed to other middleware that needs the requestId. (see: https://github.com/atlassian/glogrus/commit/69a9fbb499c8338ab28521dff77726e28a85d941)

**Comment by zenazn** [comment]
This issue has been idle for quite a few months now, so I'm closing it to keep everything tidy. Since Goji has standardized on net/http interfaces, I'm delighted to say that this problem can be solved Mux-agnostically, and no longer needs to be done under the "Goji" umbrella.
