### ISSUE TITLE
New repo request: glogrus2

### ISSUE THREAD

**Issue by jdoklovic** [goji/goji#19]
I'd like to have  anew repo under goji created called "goji/glogrus2"
This is a port of the original glogrus project to goji2

The contents of this repo should contain what's in this branch:
https://github.com/atlassian/glogrus/tree/goji2

Not only does this include the update to goji2, but it also provides a pluggable way to retrieve requestId from the http Context. see: https://github.com/atlassian/gojiid

For more info on why I'm requesting this repo, see: https://github.com/goji/glogrus/pull/2

**Comment by zenazn** [comment]
Done! https://github.com/goji/glogrus2

**Comment by jdoklovic** [comment]
@zenazn Thanks! I'll get this setup today
