### ISSUE TITLE
import goji.io not working

### ISSUE THREAD

**Issue by donseba** [goji/goji#2]
Hello, I wanted to try to package to compare it against "zenazn/goji" but the import paths are set to 

"goji.io" instead of "github.com/goji/goji" . 

Is there an spicific reason for this?

BTW : Thanks for your time and effort

**Comment by elithrar** [comment]
The package isn't ready for real world use yet (in that the API might
change) so you will need to clone it into $GOPATH/src/goji.io/

**Comment by donseba** [comment]
okay thank you

**Comment by mwmahlberg** [comment]
Does it make sense then to have it documented like this in the README.md?
