### ISSUE TITLE
NotFound Handler

### ISSUE THREAD

**Issue by saj1th** [goji/goji#20]
The "notFound Handler" was a neat convenience in zenazn/goji 

https://github.com/goji/goji/blob/master/router_trie.go doesn't seem to have a similar concept - probably because you decided to make less assumptions in goji2

I'm wondering what would be the best way to implement a custom 404 handler with goji2

thanks for new libs

**Comment by zenazn** [comment]
Since routing is now performed before the middleware stack, you can now do this yourself! Just take a peek at the matched `Handler` (by calling https://godoc.org/goji.io/middleware#Handler), and if it's `nil`, no route was matched, and a 404 should be served.

**Comment by saj1th** [comment]
Cool. thanks!

**Comment by alexguan** [comment]
This does not work well when you have SubMix. For example:

```golang
rootMux := goji.NewMux()
v1Mux :=goji.SubMux()

rootMux.HandleC(pat.New("/v1/*"), v1Mux)
v1Mux.HandleC(pat.Get("/foo"), FooHandler)

```

Then there seems no way to return a customized 404 for `/v1/bar` since `middleware.Handler` will return a non-nil handler (which is `v1Mux`);

Any ideas?

**Comment by saj1th** [comment]
@alexguan  

looks like the hacky way around the problem is to apply the 404 middleware to your sub muxes as well

```
rootMux := goji.NewMux()
v1Mux :=goji.SubMux()
rootMux.UseC(middleware.Apply404)
v1Mux.UseC(middleware.Apply404)

rootMux.HandleC(pat.New("/v1/*"), v1Mux)
v1Mux.HandleC(pat.Get("/foo"), FooHandler)

```
Like you mentioned, while https://github.com/goji/goji/blob/9798f3919ceac1759f98777d9624ac82e8e35f41/dispatch.go#L14 would get a nil handler, https://github.com/goji/goji/blob/9798f3919ceac1759f98777d9624ac82e8e35f41/middleware/middleware.go#L52 would not get nil as a *goji.Mux would be present.

Let me know if you found a better way to tackle this?

@zenazn  thoughts?

**Comment by alexguan** [comment]
@saj1th The workaround is rather ugly since you need to apply the middleware to all sub muxes. It seems the right way to do it is to enhance `Mux` to provide a hook so we can supply a function to override the default `NotFound` behavior.

@zenazn Any other suggestions?

**Comment by zenazn** [comment]
You can write an abstraction to create new `Mux`'s with a `NotFound` middleware attached, instead of using `goji.NewMux`. If you want to cast a wider net, you can also write a `http.ResponseWriter` implementation that catches 404 status codes and instead renders a different 404.

Trying to auto-detect `SubMux`es and do something more clever sacrifices the principle of least surprise, however, since it means the two snippets below would behave differently—there is no way to determine if a given `goji.Handler` logically implements a `SubMux`:

```
rootMux := goji.NewMux()
v1Mux := goji.SubMux()

rootMux.HandleC(pat.New("/v1/*"), v1Mux)
v1Mux.HandleC(pat.Get("/foo"), FooHandler)
```

```
rootMux := goji.NewMux()
v1Mux := goji.SubMux()

shim := func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
    v1Mux.ServeHTTPC(ctx, w, r)
}

rootMux.HandleC(pat.New("/v1/*"), goji.HandlerFunc(shim))
v1Mux.HandleC(pat.Get("/foo"), FooHandler)
```

**Comment by zenazn** [comment]
For prior art on a `http.ResponseWriter` shim, I wrote a reasonable implementation as part of the previous version of Goji: https://godoc.org/github.com/zenazn/goji/web/mutil. The code is based entirely on the `net/http` interfaces, however, and can be reused with any mux of your choice, including this version of Goji.

**Comment by alexguan** [comment]
@zenazn I understand your concerns, however, it feels to me that such a basic need should be directly supported by the framework, instead of asking everyone to duplicate the work.

**Comment by zenazn** [comment]
Even if Goji provided some kind of `NotFound` capability, it would have to be manually applied to every `Mux`, which doesn't seem like a win to me. Is there something I'm missing?
