### ISSUE TITLE
Need to abandon middleware in sub mux

### ISSUE THREAD

**Issue by jdoklovic** [goji/goji#21]
@zenazn 
So while I was messing with a logging middleware, I was printing out middleware.Pattern(ctx) in the log as the url that was hit, but when this is set on the root mux and you have a sub-mux, you'll never get the right pattern.

example:
```
root := goji.NewMux()
users := goji.SubMux()

//setup logging at the root mux
root.UseC(NewLoggerMiddleware())

root.HandleFunc(pat.Get("/my-app"), IndexHandler)
root.Handle(pat.Get("/my-app/*"), subRouter)

subRouter.HandleFuncC(pat.Get("/some-route"),SomeHandler)

// logging middleware does something like this:
fmt.Println(middleware.Pattern(ctx)
```
When you call /my-app, the log prints "/my-app". that's fine
But when you hit /my-app/some-route" the log will always print "/my-app/*". This is because the logger was added on the root mux and that's the pattern that was matched on the root mux. That makes sense.

Unfortunately, If I also add the logger to the sub-mux, I'll get 2 log entries for every request, which is not what I want.

I should be able to do:
```
subRouter.Abandon(root.NewLoggerMiddleware)
subRouter.UseC(NewLoggerMiddleware)
```

So, some of the time I have middleware that's truly global and I don't care if it runs on the root context, but other times, I want to have a "sepecial" instance of the middleware for a sub-mux that overrides the instance on the root mux

**Comment by jdoklovic** [comment]
Actually, I was able to work around my issue by using a couple more muxs.

**Comment by zenazn** [comment]
I know you've found a workaround, but a brief comment on something you mentioned:

```
subRouter.Abandon(root.NewLoggerMiddleware)
subRouter.UseC(NewLoggerMiddleware)
```

Unfortunately, this can't possibly work: `root.NewLoggerMiddleware` has already happened by the time `subRouter` gets a chance to look at the request. The rough mental model here is that sub Muxes are not special at all—they are just `Handler`s like everything else—and that middleware always happens immediately before `Handler`s execute.

**Comment by troylelandshields** [comment]
@jdoklovic, can you describe your workaround? We are having the same issue.

**Comment by jdoklovic** [comment]
@troylelandshields The work around was to expand everything into their own routers and then apply logging middleware to each sub router. The root router doesn't have logging middleware at all and also has no actual routes other than mapping patterns to sub routers
