### ISSUE TITLE
Wildcard matched parameter

### ISSUE THREAD

**Issue by mandeepbrar** [goji/goji#23]
Can i get the wild card match as a parameter e.g. if i did mux.HandleFuncC("/\*", myhandler). Can i do it as mux.HandleFuncC("/\*param", myhandler). Can I get the parameter param from the context later

**Comment by zenazn** [comment]
You can indeed! https://godoc.org/goji.io/pattern#Path

(Although as a practical note that method will return a escaped path, which you'll have to un-escape if that matters to your application)
