### ISSUE TITLE
Match route in middleware

### ISSUE THREAD

**Issue by vidfamn** [goji/goji#25]
Hi,

I'm updating my app and trying to port a bit of route matching in a middleware from zenazn/goji to goji/goji. I can't get the new `pattern.Match(ctx, r)` to match in the same way as the older `pattern.Match(r, c)`. I was wondering if you know why this doesn't work?
### Examples

[gojipatterntest.txt](https://github.com/goji/goji/files/220539/gojipatterntest.txt)
Output:
`no match..
no match..
no match..`

[zenazngojipatterntest.txt](https://github.com/goji/goji/files/220540/zenazngojipatterntest.txt)
Output:
`no match..
no match..
match!`

Just to clarify, the results from example zenazngojipatterntest is what I'm expecting, with a match on `/hello/:name`. The example gojipatterntest doesn't match this, am I missing something?

**Comment by vidfamn** [comment]
I solved my use case in a bit dubious manner with a type assert and string matching instead of using the `pattern.Match(ctx, r)` function.

Example below, if anyone has a similar issue while porting middleware from zenazn/goji to goji/goji.
```go
package main

import (
	"fmt"
	"net/http"

	"goji.io"
	"goji.io/middleware"
	"goji.io/pat"
	"golang.org/x/net/context"
)

func hello(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	name := pat.Param(ctx, "name")
	fmt.Fprintf(w, "Hello, %s!", name)
}

var routes = []string{
	"/", "/hello", "/hello/:name",
}

func myMiddleware(h goji.Handler) goji.Handler {
	fn := func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		gojiPattern := middleware.Pattern(ctx)
		if gojiPattern == nil {
			h.ServeHTTPC(ctx, w, r)
			return
		}

		requestResource := gojiPattern.(*pat.Pattern).String()

		for _, resource := range routes {
			if requestResource == resource {
				fmt.Println("matched saved resource!")
				// do stuff
				break
			}
		}

		h.ServeHTTPC(ctx, w, r)
	}

	return goji.HandlerFunc(fn)
}

func main() {
	mux := goji.NewMux()
	mux.HandleFuncC(pat.Get("/hello/:name"), hello)
	mux.UseC(myMiddleware)

	http.ListenAndServe("localhost:8000", mux)
}
```

**Comment by zenazn** [comment]
This issue has been idle for a few months now, so I'm closing it to keep everything tidy. It looks like you were able to solve your problem using type assertions in middleware, but if you're still in the market for solutions this might be the sort of problem that is best solved using custom `Pattern` types.
