### ISSUE TITLE
Unexpected route/middleware execution order

### ISSUE THREAD

**Issue by eriklott** [goji/goji#26]
Example:

```
mux := goji.NewMux()
mux.UseC(middlewareThatChangesRequestPostToPut)
mux.HandleC(pat.Put("/somepath"), someHandler)
```

I was surprised to find that writing middleware to change the request.Method from POST to PUT would not effect the route pattern matcher on line 3. Looking at the source comments, it seems that routes are parsed before middleware is run. Is there a reason for that? 

To get this to work properly, I'll need to wrap the mux itself...

```
mux := goji.NewMux()
mux.HandleC(pat.Put("/somepath"), someHandler)

http.Handle("/", middlewareThatChangesRequestPostToPut(mux))
```

As middleware is added to the mux, I think the natural assumption is that it is going to affect all middleware **and handlers** lower in the stack. Is there any interest in having this changed?

**Comment by zenazn** [comment]
This is expected and documented behavior: https://godoc.org/goji.io#Mux.Use

> Middleware in Goji is called after routing has been performed. Therefore it is possible to examine any routing information placed into the context by Patterns, or to view or modify the Handler that will be routed to. Middleware authors should read the documentation for the "middleware" subpackage for more information about how this is done.

For historical context, the previous version of goji (`zenazn/goji`) did things the other way around (middleware first and routing after), and in practice people found that behavior more confusing, since they expected routing information (i.e., the matched pattern and handler) to be available in the middleware stack. The current design lacks an official way to express pre-routing middleware, but as you've discovered it's pretty easy to do that yourself (another common technique is to create a dummy `Mux` with a single catch-all route, and to register pre-routing middleware on the dummy `Mux`).

I've definitely thought about trying to do something fancier like you suggest, but every proposal I've come up with seems to introduce hard-to-document ordering dependencies, which feels brittle to me. It's possible there's an easy design fix here, but I don't know what it is, and in my use of Goji it rarely comes up anyways.

**Comment by eriklott** [comment]
@zenazn Thanks for getting back.

Actually, I think that Goji is slightly more complex than it needs to be. Rather than providing users with a Mux, which wraps routing endpoints with middleware (complex), why not just provide users with a simple middleware stack? For example:

```
stack := goji.NewStack()
stack.Use(mymiddleware1) //<-- runs first
stack.Use(mymiddleware2) //<-- runs second
stack.Use(mymiddleware3) //<-- runs third
... etc

http.Handle("/", stack)
```

To introduce routing, users can use routing middleware:

```
stack := goji.NewStack()
stack.Use(mymiddleware1) //<-- runs first
stack.Use(mymiddleware2) //<-- runs second
stack.Use(goji.RouteMiddlware(pat.Get("/mypath"), myhandler)) //<-- runs third
stack.Use(mymiddleware3) //<-- runs forth
stack.Use(goji.RouteMiddlware(pat.Get("/anotherpath"), anotherhandler)) //<-- runs fifth
... etc

http.Handle("/", stack)
```
...And we can create a convenience method - `Route` -  to wrap the `RouteMiddlware`...

```
stack := goji.NewStack()
stack.Use(mymiddleware1)
stack.Use(mymiddleware2)
stack.Route(pat.Get("/mypath"), myhandler)
stack.Use(mymiddleware3)
stack.Route(pat.Get("/anotherpath"), anotherhandler)
... etc

http.Handle("/", stack)
```

This imaginary "stack" and the current Goji Mux are nearly identical, except the stack has no surprises or special behaviour. Thoughts?

**Comment by zenazn** [comment]
That's pretty tricky to make run efficiently, unfortunately. And while it's certainly a smaller API, I'm not sure it's actually easier to understand, especially for the common case.

I'd certainly encourage you to try this out, though—`goji.RouteMiddlware` is easy enough to write on your own, and I'd be curious to hear how nice you find the resulting abstraction.

**Comment by eriklott** [comment]
@zenazn  I'm not sure if I follow. What is the common case?

**Comment by zenazn** [comment]
I think that most people do not require such tight control over execution order, and that most of the use of Goji is for its routing layer (and the improvement there over `net/http`) and not its middleware stack. For me, this means that Goji should be primarily focused on making routes easy to understand and add, and less focused on making middleware the single core abstraction.

**Comment by eriklott** [comment]
Keep in mind, the middleware as single core abstraction is strictly an internal change. The API stays unchanged for the user. Here is my example from above:

```
stack := goji.NewStack()
stack.Use(mymiddleware1)
stack.Use(mymiddleware2)
stack.Route(pat.Get("/mypath"), myhandler)
stack.Use(mymiddleware3)
stack.Route(pat.Get("/anotherpath"), anotherhandler)
... etc

http.Handle("/", stack)
```

And here is the example with methods and structs renamed to idiomatic Go to make things familiar:

```
mux := goji.NewMux()
mux.Use(mymiddleware1)
mux.Use(mymiddleware2)
mux.Handle(pat.Get("/mypath"), myhandler)
mux.Use(mymiddleware3)
mux.Handle(pat.Get("/anotherpath"), anotherhandler)
... etc

http.Handle("/", mux)
```

The API is the same.

> I think that most people do not require such tight control over execution order,

I would respectfully disagree. Execution order is generally significant, and is best when explicit and un-magical. Goji is generally already programmed this way. When you add middleware to the Mux, they execute in order. And when you add routes to the mux, I would expect that they are evaluated in order (I hope). It is surprising and unintuitive when things don't execute in order, much like go.http is surprising when developers discover that routes don't evaluate in order, but by best match. It's not necessarily incorrect, but it's not intuitive.

Using the example code above, if I make a request GET "/mypath", I expect my execution order to be:

```
mux.Use(mymiddleware1)  // 1
mux.Use(mymiddleware2)  // 2
mux.Handle(pat.Get("/mypath"), myhandler)  // 3
```

and not:

```
mux.Use(mymiddleware1)  // 2
mux.Use(mymiddleware2)  // 3
mux.Handle(pat.Get("/mypath"), myhandler)  // 1
```

If my middleware adjusts the request object for some reason, this change will need to occur before it hits the router. 

If I want middleware to be run after route matching, I'd provide an explicit api similar to nodejs:

```
mux.Use(mymiddleware1)
mux.Use(mymiddleware2)
mux.Handle(pat.Get("/mypath"), mymiddleware3, mymiddleware4, myhandler)
```

> For historical context, the previous version of goji (zenazn/goji) did things the other way around (middleware first and routing after), and in practice people found that behavior more confusing, since they expected routing information (i.e., the matched pattern and handler) to be available in the middleware stack. 

In my experience, these people may have only needed a little assistance creating well encapsulated middleware, rather than an API change.

**Comment by zenazn** [comment]
This issue has been idle for a few months now, so I'm closing it to keep everything tidy. Since you wrote in, I've made a few changes to the public API, which you'll hopefully find simpler and easier to use. But while I'm a big fan of the abstraction of middleware, I'm afraid we're going to have to agree to disagree with how to structure Goji.
