### ISSUE TITLE
Can not use to GAE?

### ISSUE THREAD

**Issue by funnythingz** [goji/goji#27]
Hi!

can not use to GAE?

```sh
go-app-builder: Failed parsing input: parser: bad import "syscall" in vendor/golang.org/x/net/internal/nettest/rlimit_unix.go
```

I think had been used before ?

**Comment by elithrar** [comment]
The syscall package is the issue, which Goji doesn't import. Are you
importing syscall directly or using a package that imports it?

**Comment by funnythingz** [comment]
sorry... I had to miss the set of gopath...

thanks!!
