### ISSUE TITLE
Allow omitting trailing slash when using goji.SubMux() sub routers

### ISSUE THREAD

**Issue by Sironfoot** [goji/goji#28]
When using a SubMux() sub router, I am forced to use a trailing slash on the end of the URL. For instance, given the following:

````
foo := goji.SubMux()
root.HandleC(pat.New("/foo/*"), foo)

foo.HandleFuncC(pat.Get("/"), getAllFoos)
foo.HandleFuncC(pat.Get("/:fooID"), getSingleFoo)
````

I have to use `/foo/` instead of `/foo` which returns a 404. I have read https://github.com/zenazn/goji/pull/97 and am sold on the idea that /foo and /foo/ should be treated as 2 different URLs. But in my case I'd rather have /foo be the canonical one, and /foo/ return a 404, or maybe a 301 permanent redirect to /foo.

For a public facing Rest API I believe users (developers) are more likely to accidentally omit the slash, and while I could 301 redirect /foo to /foo/ with middleware, I'm not sure how this would play with badly coded clients that don't auto follow redirects, or the extra overhead of the redirect happening for every request.

I know it's a small thing and I can live with it. It's just one small annoyance in an otherwise perfect http request multiplexer. Keep up the excellent work :-)

### Workarounds:

So of course I could just not use SubMux and declare all the URLs on the root router, but then I lose the benefits of sub router specific middleware. I could also have /foo 301 permanent redirect to /foo/ which is what I'm currently doing.

**Comment by zenazn** [comment]
One other workaround that I'm preeeettty sure will work is the following:

``` go
foo := goji.SubMux()
root.HandleC(pat.New("/foo/*"), foo)
root.HandleC(pat.New("/foo"), foo)

foo.HandleFuncC(pat.Get("/"), redirect)
foo.HandleFuncC(pat.Get(""), getAllFoos)
```

**Comment by zenazn** [comment]
(The principle behind this is that `goji.Mux`'s, even `SubMux`es, can act as vanilla `goji.Handler`s as well)

**Comment by Sironfoot** [comment]
Works perfectly, thanks! You can close this now :-)
