### ISSUE TITLE
Suggested Way To Handle 404 Errors

### ISSUE THREAD

**Issue by derekdowling** [goji/goji#29]
I know that by default if a match isn't found within Goji, http.NotFound is called. How do you recommend handling this case with a custom handler? It looks like I could potentially use a route, but I'm not sure there is a guarantee about route matching order? Thanks!

**Comment by elithrar** [comment]
See https://github.com/goji/goji/issues/20 (answer: middleware)

**Comment by zenazn** [comment]
While I still wholeheartedly recommend writing a middleware to generate custom 404s, it turns out Goji actually does have a very well defined route matching order: https://godoc.org/goji.io#Mux.Handle

**Comment by zenazn** [comment]
This issue has been idle for a few months now, so I'm closing it to keep everything tidy. Hopefully you were able to use the technique in #20 to good effect!
