### ISSUE TITLE
Go 1.7 + http.Request.Context()

### ISSUE THREAD

**Issue by elithrar** [goji/goji#34]
@zenazn - is there still a plan to break the API?
- Will `mux.HandleC/HandleFuncC` be kept?
- Will they be rolled into `mux.Handle/HandleFunc`?
- `Use/UseC`?

I'm for breaking it—Goji v2 is fairly new and has lived in the world of vendoring, which makes it more likely (but not guaranteed!) that users who care have vendored the package. It would also reduce the API, which is a plus.

**Comment by desimone** [comment]
A quick bump because Go 1.7 was released today. @zenazn if you can direct on the above, and breaking the API is still the plan, I'm available to help make this happen.

**Comment by ottob** [comment]
For reference: some work on this has already been done in https://github.com/goji/goji/pull/30.

But I'm also curious about the future of the project.

**Comment by zenazn** [comment]
Sorry for the delay, folks—had a bit of time on a recent flight and whipped together a re-imagining of the Goji API with the recent Go 1.7 changes. It's quite similar to #30, with one additional change: the `Pattern` interface's `Match` method now has signature `func(*http.Request) *http.Request`.

It's on the `go17` branch, and I encourage folks to give it a shot. Let me know what you think!

I haven't decided if this is worth breaking backwards compatibility over. I'm leaning towards "yes"

**Comment by elithrar** [comment]
@zenazn LGTM. The (much) simpler API is a big win.

**Comment by desimone** [comment]
@zenazn LGTM. I'm a fan of the new, slimmer API as well.

**Comment by zenazn** [comment]
Would people find it onerous if package middleware and package pattern used `*http.Request` instead of `context.Context` as the base type? I'm looking to discourage people from retrieving this information in places far removed from HTTP request handling. (the underlying storage mechanism would remain unchanged)

**Comment by elithrar** [comment]
@zenazn Makes sense to me.

**Comment by desimone** [comment]
> I'm looking to discourage people from retrieving this information in places far removed from HTTP request handling. 

I agree. Makes sense to me. But, what are your concerns with using `context.Context` far removed from request handling? What scenarios are you thinking of?

**Comment by moorereason** [comment]
@zenazn, I was actually thinking the same thing yesterday while playing with the `go17` branch.  I can't think of a reason why that would be a problem, but my uses of Goji are rather straight forward.  Conceptually, it makes more sense to me to pass the Request around instead of the Context. :+1:

**Comment by ekanna** [comment]
@zenazn eagerly waiting for go17 branch merge with master!

**Comment by nqv** [comment]
@zenazn do you have any timeline for merging go17 branch?

**Comment by zenazn** [comment]
Alright, I've taken the plunge and merged the `go17` branch. Users of the old API are encouraged to switch to the `net-context` branch, which I also promise to maintain. I've rewritten the stability section of the README to reflect this change.

Please reach out to me if you have Opinions™.
