### ISSUE TITLE
Problem in running goji "Hello World"

### ISSUE THREAD

**Issue by sengkathir** [goji/goji#44]
Hi,

I am trying to set up a new project. I am not able to run "hello world" program.

Initially,
`go build` exits with error
```
vendor/goji.io/internal/http.go:6:2: cannot find package "golang.org/x/net/context" in any of:
	/workspace/src/sengkathir/vendor/golang.org/x/net/context (vendor tree)
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/workspace/src/golang.org/x/net/context (from $GOPATH)
```

Upon installing `context` package, again `go build` exists with 

```
./main.go:12: cannot use r (type *http.Request) as type "sengkathir/vendor/golang.org/x/net/context".Context in argument to pat.Param:
	*http.Request does not implement "sengkathir/vendor/golang.org/x/net/context".Context (missing Deadline method)

```

$ go version
go version go1.7.3 darwin/amd64

goji version
```
- package: goji.io
  version: v1.0
```

Am I missing something?

Thanks!

**Comment by ekanna** [comment]
Run below update command and try again
```
go get -u goji.io
```

**Comment by zenazn** [comment]
This issue has been idle for a few months now, so I'm closing it to keep everything tidy. If running `go get -u` didn't help, please feel free to re-open this ticket!
