### ISSUE TITLE
Can't install goji

### ISSUE THREAD

**Issue by kovirolik** [goji/goji#48]
`kovirolik@castle ~ $ go get goji.io`
`
package context: unrecognized import path "context"
`

**Comment by kovirolik** [comment]
Go version
`kovirolik@castle ~ $ go version
go version go1.5.2 linux/amd64
kovirolik@castle ~ $ 
`

**Comment by renstrom** [comment]
You need at least Go 1.7, because that's when `golang.org/x/net/context` got merged into the standard library. https://golang.org/doc/go1.7#context

**Comment by kovirolik** [comment]
Thank you , @renstrom !
