### ISSUE TITLE
Cannot install using glide or gb

### ISSUE THREAD

**Issue by nullstyle** [goji/goji#51]
Our CI suite broke today because of an issue that appears to be related to goji.io and it's import configuration.

From glide: https://travis-ci.org/stellar/go/jobs/214654596
```
[WARN]	Unable to checkout goji.io
[ERROR]	Update failed for goji.io: Cannot detect VCS
[INFO]	--> Fetching golang.org/x/crypto.
[INFO]	--> Fetching golang.org/x/net.
[INFO]	--> Fetching golang.org/x/sys.
[INFO]	--> Fetching gopkg.in/gavv/httpexpect.v1.
[INFO]	--> Fetching gopkg.in/tylerb/graceful.v1.
[ERROR]	Failed to install: Cannot detect VCS
```

From gb: https://travis-ci.org/stellar/horizon/jobs/214687970
```
FATAL: command "restore" failed: could not process dependency: unable to determine remote metadata protocol: failed to access url "https://goji.io?go-get=1"
FATAL: command "vendor" failed: exit status 1
```

Please advise.  Thanks!

**Comment by zenazn** [comment]
Oops sorry! That was me renewing Goji's SSL cert and screwing something up in the GCE webface. Won't happen again (for another year)! (Although hopefully by then Google will be able to auto-issue certificates like Amazon)

**Comment by zenazn** [comment]
(At least I think that's what happened. If you're still having trouble there might be something else happening)

**Comment by nullstyle** [comment]
Hmm, still getting the same issue:  https://travis-ci.org/stellar/horizon/jobs/214687970#L571

**Comment by zenazn** [comment]
@nullstyle alright—give that a shot?

**Comment by zenazn** [comment]
(I shredded the private key the cert was issued to, so had to reissue 😧)

**Comment by nullstyle** [comment]
Bingo!  Thanks so much for your quick work and fix.  I appreciate it :)
