### ISSUE TITLE
go get issue

### ISSUE THREAD

**Issue by lkmadushan** [goji/goji#52]
```
Golang/src/github.com/goji/goji/dispatch.go:6:2: use of internal package not allowed
```

this happened when i try to download goji package

**Comment by Marahin** [comment]
@lkmadushan why exactly did you close the issue? I still am receiving it.

**Comment by zenazn** [comment]
In case others stumble upon this issue, it's likely because you're running `go get github.com/goji/goji`. The correct import path for Goji is `go get goji.io`.
