### ISSUE TITLE
dispatch.go:6:2: use of internal package not allowed

### ISSUE THREAD

**Issue by Marahin** [goji/goji#53]
During `go get` I get an error message:
`/go/src/github.com/goji/goji/dispatch.go:6:2: use of internal package not allowed` - which exits `go get` with error code, however the source code is still downloaded & usable in my programs.

This however makes creating Makefile dependency-fulfilling rules impossible, along with creating CI scripts that would require all the commands to return no-error code.

**Comment by zenazn** [comment]
It looks like you've run `go get github.com/goji/goji`, but per https://goji.io Goji actually has a vanity URL: `go get goji.io`. Give that a shot!
