### ISSUE TITLE
go modules support ?

### ISSUE THREAD

**Issue by ekle** [goji/goji#58]
the new go modules allow to fetch versions with go get.
but this does not seem to work:
```
go get goji.io@v1.1
go get goji.io@v1.1: no matching versions for query "v1.1"
```

**Comment by elithrar** [comment]
You can only fetch a Go package by its version if it explicitly defines itself as a valid Go Module - through the presence of a valid `go.mod` file.

Goji isn’t a Module, and thus you can’t use `go get` like that.

**Comment by zenazn** [comment]
Good news! Just added module support. Let me know if you’re still having trouble with this

**Comment by ekle** [comment]
hi,
it still does not work. But i think that is because of the git-tags.
go modules requires `vX.Y.Z` tags. it looks like it does not work with `vX.Y` tags.

```
GO111MODULE=on go get -u -v goji.io@v1.1
  Fetching https://goji.io?go-get=1
  Parsing meta tags from https://goji.io?go-get=1 (status code 200)
  get "goji.io": found meta tag get.metaImport{Prefix:"goji.io", VCS:"git", 
  RepoRoot:"https://github.com/goji/goji"} at https://goji.io?go-get=1
  go get goji.io@v1.1: no matching versions for query "v1.1"
```

**Comment by zenazn** [comment]
Alright—I’ve gone and added three-part semvar tags. Let me know if that helps!
