### ISSUE TITLE
how to HTTPS/TLS Web Server with goji ?

### ISSUE THREAD

**Issue by bokunodev** [goji/goji#66]
godoc.org/goji.io didn't mention anything about SSL/TLS in goji
am i miss something ?

**Comment by elithrar** [comment]
Goji doesn’t prevent you from using TLS: Go’s built-in TLS server works
with Goji -
https://golang.org/pkg/net/http/#ListenAndServeTLS

Passing your *goji.Mux to server.Handler or to ListenAndServeTLS will work.
