### ISSUE TITLE
Godoc "Not Found"

### ISSUE THREAD

**Issue by derekdowling** [goji/goji#8]
Not sure what is going wrong here, but your links aren't working for: https://godoc.org/goji.io :(

**Comment by elithrar** [comment]
In the meantime, use https://godoc.org/github.com/goji/goji

Note: from a quick 5 minute skim of the <meta> tags on goji.io and the
godoc Wiki I can't see why it's not working. @zenazn may have to take a
look later.

**Comment by zenazn** [comment]
Tracking at https://github.com/golang/gddo/issues/355 and https://github.com/golang/go/issues/13506

**Comment by elithrar** [comment]
Did you want to (temporarily) amend the GoDoc link on http://goji.io/ to link to the goji/goji repo, unti this is fixed?

**Comment by zenazn** [comment]
Good idea—this is taking longer to address than expected (likely due to the holidays). Fixed! (or, rather, temporarily worked around!)

**Comment by zenazn** [comment]
Good news! This got fixed
