### ISSUE TITLE
Listing all routes within a Mux

### ISSUE THREAD

**Issue by derekdowling** [goji/goji#9]
Is there any way to list all registered routes within a Mux? This is useful for debugging purposes to ensure everything as it seems, and I'd like to work on some route auto-generation tools. I understand if this isn't feasible, but it'd definitely be nice to have!

**Comment by zenazn** [comment]
There's not really a great way of doing this, unfortunately. Goji accepts routes in multiple forms (i.e., the regex `Handle(Func)?(C)?`), and there's no type that these four types satisfy except `interface{}`.

If I may ask, why would being able to list routes be useful for route auto-generation? I'd like to support people auto-generating routes, but I don't quite understand why listing routes would be helpful for this.

**Comment by donseba** [comment]
Hello, this is an similar question I had on the other [zenazn/goji](https://github.com/zenazn/goji/issues/170) repo . 

Therefor I've made an package [webdoc](https://github.com/donseba/webdoc) it is modified to use the goji.io repo .

**Comment by derekdowling** [comment]
@zenazn I sort of figured that might be the case. I should specify, what I was really hoping to do was auto-generate documentation for an API, similar to what @donseba has done in his library. It makes sense though that it might be difficult with so many unique potential entry points into the API.

**Comment by derekdowling** [comment]
Since inquiring about this, I've run into a case in which I was using sub-routing functionality with Goji improperly (not respecting that goji.Pat strips matched pieces before passing to sub-routers). I was forced to manually debug which routes exist by dumping variables from: https://github.com/goji/goji/blob/master/router_trie.go#L67. Could the router be leveraged to provide some sort of printable method & route tree?

**Comment by donseba** [comment]
Hello @derekdowling , I asked @zenazn rougly the same question here : [question](https://github.com/zenazn/goji/issues/170) . and you can read his thoughts about it there.

**Comment by derekdowling** [comment]
Ahh, I see this conversation has already been had: https://github.com/zenazn/goji/issues/170 closing.

**Comment by zenazn** [comment]
@derekdowling: I think I can write a middleware layer that would have helped you out there: you can attach it into your muxes and it can print out the pattern and handler that was matched, as well as the path and bound variables.

But sorry about the sub-router confusion: it's easily the most magic part of Goji, and might just be more confusion than it's worth.

**Comment by derekdowling** [comment]
Nope, it's definitely a good idea, it probably just requires some better documentation within Goji itself how to set that up. Where would you prefer an example? In the documentation or in the README? I can whip one up.
